steps:
  # Step 1: Build the Docker image for the backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-image', './back-end']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-image']

  # Step 3: Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - backend-service
      - --image=gcr.io/$PROJECT_ID/backend-image
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated
      - --port=8080
      - --set-env-vars=NODE_ENV=production,PORT=8080,SESSION_SECRET=$SESSION_SECRET,PGDATABASE=$PGDATABASE,PGHOST=$PGHOST,PGPASSWORD=$PGPASSWORD,PGPORT=$PGPORT,PGUSER=$PGUSER,GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET,REACT_PYTHON_APP_API_BASE_URL=$REACT_PYTHON_APP_API_BASE_URL,FRONT_END_BASE_URL=$FRONT_END_BASE_URL

# Substitute these with the relevant variables in your Google Cloud Project
substitutions:
  _PGDATABASE: 'postgres'
  _PGHOST: '35.221.38.242'
  _PGPASSWORD: 'root'
  _PGPORT: '5432'
  _PGUSER: 'postgres'
 _REACT_PYTHON_APP_API_BASE_URL: 'https://verta-service-294113686552.us-east1.run.app'
  _FRONT_END_BASE_URL: 'http://localhost:3000'

images:
  - 'gcr.io/$PROJECT_ID/backend-image'
