steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/ecom-chatbot-ui:$COMMIT_SHA',
      '.'
    ]
    timeout: '1200s'

  # Step 2: Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/ecom-chatbot-ui:$COMMIT_SHA'
    ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ecom-chatbot-ui'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ecom-chatbot-ui:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--port'
      - '8080'
      - '--max-instances'
      - '100'
      - '--min-instances'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--service-account'
      - '403080441770-compute@developer.gserviceaccount.com'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/ecom-chatbot-ui:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _REGION: 'us-east1'
  _SERVICE_NAME: 'ecom-chatbot-ui'